version: '3.8'
services:
  database:
    container_name: laaravel_acl_postgres
    image: postgres
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${DB_PORT}:5432"
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_TCP_PORT: ${DB_PORT}

    volumes:
      # - ./database/docker/container_postgres:/var/lib/postgres
      - ${DB_CONTAINER}
  cache:
      container_name: laaravel_acl_redis
      image: redis
      restart: always
      ports:
        - "${REDIS_PORT}:6379"
      expose:
        - ${REDIS_PORT}
      environment:
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
